### ISSUE TITLE
mac版本还需等待何时？

### ISSUE THREAD

**Issue by bwnjnOEI** [LiangJianyi/VisualizationRecorder#1]
mac版本还需等待何时？

**Comment by KinyetLeaung** [comment]
目前还在探索SwiftUI，SwiftUI好像没有和UWP等价的Canvas容器，我还没有找到让Rectangle自定义布局的办法（比如将若干个Rectangle重叠在一起），不知道你是否有解决方案？
[cid:EAF57149-D0C4-4A37-A4DC-3B966E62BD1A]

On Mar 24, 2020, at 09:20, bwnjn OEI <notifications@github.com<mailto:notifications@github.com>> wrote:



mac版本还需等待何时？

**Comment by bwnjnOEI** [comment]
我就是一个搞ML理论的也不会这些啊
